-- =====================================================================
-- ClassQuest — schemat bazy dla PostgreSQL (Supabase)
-- Dokument roboczy do migracji z SQLite. Aplikacja sama tworzy tabele
-- przy pierwszym starcie (CREATE TABLE IF NOT EXISTS), więc ten plik nie
-- wymaga ręcznego uruchamiania — jest wzorcem/awaryjnym zapisem.
-- Daty trzymamy jako TEXT w formacie 'YYYY-MM-DD HH:MM:SS' (identycznie
-- jak w SQLite), żeby kod aplikacji działał bez zmian.
-- =====================================================================

CREATE TABLE IF NOT EXISTS teachers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  imie_nazwisko TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  haslo_hash TEXT NOT NULL,
  rola TEXT NOT NULL DEFAULT 'nauczyciel',
  created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS klasy (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  nazwa TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS uczniowie (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  klasa_id BIGINT NOT NULL REFERENCES klasy(id) ON DELETE CASCADE,
  numer_dziennika INTEGER NOT NULL,
  imie_nazwisko TEXT NOT NULL,
  avatar_json TEXT NOT NULL DEFAULT '{}',
  xp INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
  UNIQUE (klasa_id, numer_dziennika)
);

CREATE TABLE IF NOT EXISTS zestawy_pytan (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES teachers(id) ON DELETE CASCADE,
  nazwa TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE IF NOT EXISTS pytania (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  zestaw_id BIGINT NOT NULL REFERENCES zestawy_pytan(id) ON DELETE CASCADE,
  tresc TEXT NOT NULL,
  opcja_a TEXT NOT NULL,
  opcja_b TEXT NOT NULL,
  opcja_c TEXT NOT NULL,
  opcja_d TEXT NOT NULL,
  poprawna TEXT NOT NULL CHECK (poprawna IN ('A','B','C','D')),
  czas_sek INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS sesje (
  kod TEXT PRIMARY KEY,
  teacher_id BIGINT NOT NULL REFERENCES teachers(id),
  klasa_id BIGINT NOT NULL REFERENCES klasy(id),
  zestaw_id BIGINT NOT NULL REFERENCES zestawy_pytan(id),
  tryb TEXT NOT NULL DEFAULT '4pola',
  status TEXT NOT NULL DEFAULT 'lobby',
  auto INTEGER NOT NULL DEFAULT 0,
  utworzona_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
  zakonczona_at TEXT
);

CREATE TABLE IF NOT EXISTS wyniki_gier (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sesja_kod TEXT NOT NULL REFERENCES sesje(kod) ON DELETE CASCADE,
  uczen_id BIGINT NOT NULL REFERENCES uczniowie(id) ON DELETE CASCADE,
  pozycja INTEGER NOT NULL,
  xp_zdobyte INTEGER NOT NULL DEFAULT 0,
  poprawne INTEGER NOT NULL DEFAULT 0,
  zycia_zostalo INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS xp_logi (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uczen_id BIGINT NOT NULL REFERENCES uczniowie(id) ON DELETE CASCADE,
  zrodlo TEXT NOT NULL,
  kwota INTEGER NOT NULL,
  opis TEXT NOT NULL DEFAULT '',
  sesja_kod TEXT,
  created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

CREATE INDEX IF NOT EXISTS idx_uczniowie_klasa ON uczniowie(klasa_id);
CREATE INDEX IF NOT EXISTS idx_pytania_zestaw ON pytania(zestaw_id);

-- Po utworzeniu tabel aplikacja sama zadba o to, by pierwsze konto
-- (lub konto wskazane jako 'admin') miało rolę administratora.
